import { db } from '../src/lib/db';
import { glossaryTerms } from '../src/lib/db/schema';

const sampleTerms = [
  {
    term: 'Alpha',
    definition: 'A measure of an investment\'s performance relative to a benchmark index, representing the excess return generated by active management.',
    category: 'Performance Metrics'
  },
  {
    term: 'Beta',
    definition: 'A measure of systematic risk that indicates how much a security\'s price moves relative to the overall market.',
    category: 'Risk Metrics'
  },
  {
    term: 'Credit Risk',
    definition: 'The risk that a borrower will default on their debt obligations, resulting in financial loss to the lender.',
    category: 'Credit Risk'
  },
  {
    term: 'Diversification',
    definition: 'An investment strategy that spreads risk by allocating investments across various financial instruments, industries, and other categories.',
    category: 'Risk Management'
  },
  {
    term: 'Expected Return',
    definition: 'The anticipated return on an investment based on historical data and probability distributions of possible outcomes.',
    category: 'Performance Metrics'
  },
  {
    term: 'Liquidity Risk',
    definition: 'The risk that an investor will not be able to buy or sell an investment quickly enough to prevent or minimize a loss.',
    category: 'Market Risk'
  },
  {
    term: 'Market Risk',
    definition: 'The risk of losses due to factors that affect the overall performance of financial markets, such as economic downturns or political instability.',
    category: 'Market Risk'
  },
  {
    term: 'Operational Risk',
    definition: 'The risk of loss resulting from inadequate or failed internal processes, people, systems, or external events.',
    category: 'Operational Risk'
  },
  {
    term: 'Portfolio',
    definition: 'A collection of financial investments like stocks, bonds, commodities, cash, and cash equivalents held by an individual or institution.',
    category: 'Investment Terms'
  },
  {
    term: 'Sharpe Ratio',
    definition: 'A measure of risk-adjusted return that compares the excess return of an investment to its standard deviation of returns.',
    category: 'Performance Metrics'
  },
  {
    term: 'Value at Risk (VaR)',
    definition: 'A statistical measure that quantifies the potential loss in value of a portfolio over a specific time period for a given confidence interval.',
    category: 'Risk Metrics'
  },
  {
    term: 'Volatility',
    definition: 'A statistical measure of the dispersion of returns for a given security or market index, indicating the degree of price fluctuation.',
    category: 'Risk Metrics'
  }
];

async function seed() {
  try {
    console.log('Seeding database...');
    
    // Insert sample terms
    await db.insert(glossaryTerms).values(sampleTerms);
    
    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();